# Generated by Django 4.0 on 2022-02-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('rg', models.CharField(max_length=11)),
                ('data_nasc', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(max_length=11)),
                ('cns', models.CharField(max_length=18)),
                ('telefone', models.CharField(max_length=20)),
                ('local_espera', models.TextField(help_text='Entre com uma breve descrição do local de espera.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateField(blank=True, null=True)),
                ('destino', models.CharField(max_length=200)),
                ('saida', models.CharField(help_text='HH:MM', max_length=6)),
                ('estado', models.CharField(blank=True, choices=[('C', 'Concluída'), ('P', 'Pendente'), ('E', 'Em Viagem')], default='P', help_text='Situação da Viagem', max_length=1)),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_controle.motorista')),
                ('paciente', models.ManyToManyField(help_text='Selecione os pacientes que iram nessa viagem.', to='site_controle.Paciente')),
            ],
            options={
                'ordering': ['data_viagem'],
            },
        ),
    ]
