# Generated by Django 4.0 on 2022-02-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='estado',
            field=models.CharField(blank=True, choices=[('C', 'Concluída'), ('P', 'Pendente'), ('E', 'Em Viagem'), ('A', 'Atrasado')], default='P', help_text='Situação da Viagem', max_length=1),
        ),
    ]
