# Generated by Django 4.0 on 2022-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_controle', '0002_alter_viagem_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome'], 'permissions': (('pode_manipular_paciente', 'Manipula o cadastro de pacientes.'), ('pode_criar_paciente', 'Possibilita a criação de pacientes.'))},
        ),
        migrations.AlterModelOptions(
            name='viagem',
            options={'ordering': ['data_viagem'], 'permissions': (('pode_manipular_viagem', 'Manipula o cadastro de viagens.'),)},
        ),
        migrations.AlterField(
            model_name='viagem',
            name='saida',
            field=models.CharField(max_length=6),
        ),
    ]
